[package]
name = "AlphaServer"
version = "0.1.0"
authors = ["Exopteron <exopteron@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
tokio = { version = "1.10.1", features = ["full"] }
bytes = { version = "1.1.0", features = ["serde"] }
flume = "0.10.9"
anyhow = "1.0.43"
log = "0.4.1"
env_logger = "0.9.0"
chrono = "0.4.1"
slab = "0.4.4"
flate2 = "1.0"
deflate = "0.9.1"
multiarray = "0.1.3"
glam = "0.18.0"