[package]
name = "test_plugin_1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exo_beta_server = { path = "../../" }
log = "0.4.1"
hecs = "0.6.5"
[lib]
crate-type = ["cdylib", "rlib"]